#LIBS  = -lkernel32
#CFLAGS = -Wall
#INCLS = -I ../maskern/ -I ../maslisp

# Should be equivalent to your list of C files, if you don't build selectively
SRC=$(wildcard *.c)

all: $(SRC)
	gcc  -c $@ $^  $(INCLS)  

# $(CFLAGS) $(LIBS)



